version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - docker-compose up -d db
      - docker-compose exec web rspec spec/models
  post_build:
    commands:
      - echo Build completed on `date`