version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # リポジトリのURIと名前を変数に代入
      - REPOSITORY_URI=470282350525.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_NAME=myspot
      # ECRにログイン
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${REPOSITORY_URI}
      # イメージタグとしてソースの Git コミット ID の先頭7文字を追加
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build start on `date`
      - echo Building the Docker image...
      # リポジトリの名前をタグにつけてdocker buildをする
      - docker build -t $REPOSITORY_NAME:latest .
      # リポジトリ名がついたイメージに対し、push用の名前に置き換える
      - docker tag $REPOSITORY_NAME:latest $REPOSITORY_URI/$REPOSITORY_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      # イメージをpushする
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI/$REPOSITORY_NAME:$IMAGE_TAG
      - echo Writing image definitions file...
      - echo "[{\"name\":\"rails\",\"imageUri\":\"${REPOSITORY_URI}:${IMAGE_TAG}\"}]" > imagedefinitions.json


      # printfは入力データを整形して表示するコマンド
      # %s は文字列
      #- printf '{"ImageURI":"%s"}' ${REPOSITORY_URI}/${REPOSITORY_NAME}:${IMAGE_TAG} > imageDetail.json
      #- envsubst < taskdef.template > taskdef.json

artifacts:
  files: imagedefinitions.json
    #- imageDetail.json
    #- appspec.yaml
    #- taskdef.json