# circleciのバージョン。後述するorbsを利用するためには2.1以上が必要
version: 2.1

orbs:
    # circleci/aws-ecr@6.1.0というorbをaws-ecrというaliasをつけて扱う
    aws-ecr: circleci/aws-ecr@6.1.0
    aws-ecs: circleci/aws-ecs@0.0.8

jobs:
  test:
    docker:
      - image: akito1201/myspot
      working_directory: /var/www/myspot
    steps:
      - checkout
      - run:
        name: Docker Compose のインストール
         command: |
          curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
         name: コンテナの起動とテスト
         command: |
          docker-compose up -d
          docker-compose exec web rspec spec/models



workflows:
    # build_and_push_imageという名前のworkflowを定義
    build_and_push_image:
        # workflowで実行するjobの順番を定義
        jobs:
        - test
        - aws-ecr/build-and-push-image:
            requires:
              - test
            region: AWS_REGION
            account-url: AWS_ECR_ACCOUNT_URL
            repo: 'myspot'
            tag: "${CIRCLE_SHA1}"
        - aws-ecs/deploy-service-update:
            requires:
                - aws-ecr/build-and-push-image
            family: 'myspot-real'
            cluster-name: 'myspot-cluster'
            service-name: 'myspot-service'
            container-image-name-updates: 'container=rails,tag=${CIRCLE_SHA1}'