# circleciのバージョン。後述するorbsを利用するためには2.1以上が必要
version: 2.1

orbs:
    # circleci/aws-ecr@6.1.0というorbをaws-ecrというaliasをつけて扱う
    aws-ecr: circleci/aws-ecr@6.1.0
    aws-ecs: circleci/aws-ecs@0.0.8

jobs:
  build:
    docker:
      - image: akito1201/myspot
        environment:
          - RAILS_ENV: "test"
    steps:
      - checkout
      - setup_remote_docker
      
      - run:
         name: Install Docker Compose
         command: |
          curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
          chmod +x ~/docker-compose
          mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
         name: docker-compose up
         command: |
          docker-compose up -d --build

      - run:
         name: sleep
         command: sleep 10

      - run:
         name: RSpec
         command: docker-compose exec -d web bundle exec rspec spec/models

      - run:
         name: docker-compose down
         command: |
          docker-compose down
workflows:
    # build_and_push_imageという名前のworkflowを定義
    build_and_push_image:
        # workflowで実行するjobの順番を定義
        jobs:
        - build
        - aws-ecr/build-and-push-image:
            requires:
              - build
            region: AWS_REGION
            account-url: AWS_ECR_ACCOUNT_URL
            repo: 'myspot'
            tag: "${CIRCLE_SHA1}"
            extra-build-args: '--build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY}'
        - aws-ecs/deploy-service-update:
            requires:
                - aws-ecr/build-and-push-image
            aws-region: AWS_REGION
            family: 'myspot-production'
            cluster-name: 'myspot-cluster'
            service-name: 'myspot-service'
            container-image-name-updates: 'container=rails,tag=${CIRCLE_SHA1}'